### ISSUE TITLE
Error when rendering component <post> on Homepage

### ISSUE THREAD

**Issue by nolaandy** [bedakb/vuewp#1]
I can't surf from the homepage for some reason. When I click the Sample Page link at top-right, the address bar link changes, but the page doesn't update.

When I click refresh on the Sample Page link, the page opens fine, and I'm able to surf fine between the Sample Page an the Hello World Post as pictured in your demo.

`[Vue warn]: Error when rendering component <post> at C:\Users\orion\Desktop\vuewp\public\app\themes\vuewp\app\components\Post.vue: 
warn @ main.min.js?ver=20151217:605
Vue._render @ main.min.js?ver=20151217:2307
updateComponent @ main.min.js?ver=20151217:2693
get @ main.min.js?ver=20151217:3018
Watcher @ main.min.js?ver=20151217:3010
Vue._mount @ main.min.js?ver=20151217:2692
Vue$2.$mount @ main.min.js?ver=20151217:6262
init @ main.min.js?ver=20151217:1824
createComponent @ main.min.js?ver=20151217:4258
createElm @ main.min.js?ver=20151217:4201
updateChildren @ main.min.js?ver=20151217:4471
patchVnode @ main.min.js?ver=20151217:4534
updateChildren @ main.min.js?ver=20151217:4450
patchVnode @ main.min.js?ver=20151217:4534
updateChildren @ main.min.js?ver=20151217:4450
patchVnode @ main.min.js?ver=20151217:4534
patch @ main.min.js?ver=20151217:4658
Vue._update @ main.min.js?ver=20151217:2726
updateComponent @ main.min.js?ver=20151217:2693
get @ main.min.js?ver=20151217:3018
run @ main.min.js?ver=20151217:3087
flushSchedulerQueue @ main.min.js?ver=20151217:2891
(anonymous) @ main.min.js?ver=20151217:557
nextTickHandler @ main.min.js?ver=20151217:506
main.min.js?ver=20151217:519`

`TypeError: Cannot read property 'source_url' of null
    at Proxy.render (main.min.js?ver=20151217:11397)
    at VueComponent.Vue._render (main.min.js?ver=20151217:2300)
    at VueComponent.updateComponent (main.min.js?ver=20151217:2693)
    at Watcher.get (main.min.js?ver=20151217:3018)
    at new Watcher (main.min.js?ver=20151217:3010)
    at VueComponent.Vue._mount (main.min.js?ver=20151217:2692)
    at VueComponent.Vue$2.$mount (main.min.js?ver=20151217:6262)
    at init (main.min.js?ver=20151217:1824)
    at createComponent (main.min.js?ver=20151217:4258)
    at createElm (main.min.js?ver=20151217:4201)`

Those errors don't appear when refreshing the Sample Page or Post. No errors fire in that case. Just letting you know what I'm experiencing.

**Comment by bedakb** [comment]
Hi @nolaandy thanks for reporting issue.

Just checking - have you installed all required Plugins ?

**Comment by nolaandy** [comment]
I installed all the plugins that came with the installation:
Better REST API Featured Images
FakerPress
WP REST API

**Comment by bedakb** [comment]
@nolaandy have you enabled the pretty permalinks in WP Admin ?

**Comment by nolaandy** [comment]
I do have pretty permalinks enabled, but it seems the site navigates via post id.
If I manually enter the page slug the page will load.

**Comment by nolaandy** [comment]
Weird seeing "index.php" injected into the file structure. I don't think I normally see that there. Instead of just Post Name settings, I tried switch to Custom and removing index.php but nothing changed.

![wpvue-ss](https://cloud.githubusercontent.com/assets/4950669/23378162/0a4591a0-fcf8-11e6-896e-4073a0c14dfe.jpg)

**Comment by bedakb** [comment]
FIXED - #2  - https://github.com/bedakb/vuewp/commit/d2f08655b7ebe7889a14557d7c6f4cb80c68a9d5

Fresh installation comes with the dummy post that doesn't contain featured image.There was missing check If `better_featured_image` (for articles that doesn't have featured image It's set to `null`) property exist on `item` object.It's added and It should work now.
